import type {
  DemandDistributionPoint,
  Lead,
  MatchSuggestion,
  MessageTemplate,
  Property,
  Radar,
  RadarActivityPoint,
  UserProfile,
} from "./types";

export const demoUser: UserProfile = {
  id: "user-demo",
  email: "asesor@immobil-ia.local",
  name: "Valeria Rojas",
  phone: "+57 300 555 0102",
  city: "Bogota",
  country: "Colombia",
  plan: "Pro",
  subscriptionStatus: "Activa",
  acceptedTerms: true,
};

export const demoRadars: Radar[] = [
  {
    id: "radar-chapinero",
    name: "Chapinero apartamentos",
    keywords: ["apartamento", "venta", "chapinero"],
    country: "Colombia",
    zone: "Bogota - Chapinero",
    frequency: "Semanal",
    isActive: true,
    lastRunAt: "2026-06-25T08:20:00.000Z",
  },
  {
    id: "radar-envigado",
    name: "Casas Envigado",
    keywords: ["casa", "dueno directo", "envigado"],
    country: "Colombia",
    zone: "Antioquia - Envigado",
    frequency: "Quincenal",
    isActive: false,
  },
];

export const demoProperties: Property[] = [
  {
    id: "prop-101",
    title: "Apartamento exterior 2 habitaciones",
    source: "Scraper",
    location: "Bogota - Chapinero",
    price: 420000000,
    areaM2: 72,
    rooms: 2,
    lat: 4.649,
    lng: -74.063,
    imageUrl: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=900&q=80",
    ownerName: "Carlos Marin",
    ownerPhone: "+573104455667",
    ownerEmail: "carlos.marin@example.com",
    url: "https://example.com/publicacion/prop-101",
  },
  {
    id: "prop-102",
    title: "Casa familiar con patio",
    source: "Manual",
    location: "Antioquia - Envigado",
    price: 690000000,
    areaM2: 138,
    rooms: 4,
    lat: 6.171,
    lng: -75.583,
    imageUrl: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=900&q=80",
    ownerName: "Marta Salazar",
    ownerPhone: "+573005557788",
    ownerEmail: "marta.salazar@example.com",
    url: "https://example.com/publicacion/prop-102",
  },
  {
    id: "prop-103",
    title: "Apartamento publicado por agencia aliada",
    source: "Portal",
    location: "Bogota - Chapinero",
    price: 418000000,
    areaM2: 71,
    rooms: 2,
    lat: 4.65,
    lng: -74.061,
    imageUrl: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80",
    ownerName: "Carlos Marin",
    ownerPhone: "+573104455667",
    ownerEmail: "carlos.marin@example.com",
    url: "https://example.com/publicacion/prop-103",
  },
  {
    id: "prop-104",
    title: "Casa duplicada en clasificados locales",
    source: "Red social",
    location: "Antioquia - Envigado",
    price: 705000000,
    areaM2: 140,
    rooms: 4,
    lat: 6.172,
    lng: -75.582,
    imageUrl: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=900&q=80",
    ownerName: "Marta Salazar",
    ownerPhone: "+573005557788",
    ownerEmail: "marta.salazar@example.com",
    url: "https://example.com/publicacion/prop-104",
  },
  {
    id: "prop-105",
    title: "Apartamento tipo loft cerca a parque",
    source: "Scraper",
    location: "Bogota - Usaquen",
    price: 360000000,
    areaM2: 55,
    rooms: 1,
    lat: 4.704,
    lng: -74.032,
    imageUrl: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=900&q=80",
    ownerName: "Laura Cardenas",
    ownerPhone: "+573156661212",
    ownerEmail: "laura.cardenas@example.com",
    url: "https://example.com/publicacion/prop-105",
  },
  {
    id: "prop-106",
    title: "Loft republicado con fotos similares",
    source: "Portal",
    location: "Bogota - Usaquen",
    price: 355000000,
    areaM2: 56,
    rooms: 1,
    lat: 4.705,
    lng: -74.031,
    imageUrl: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=900&q=80",
    ownerName: "Laura Cardenas",
    ownerPhone: "+573156661212",
    ownerEmail: "laura.cardenas@example.com",
    url: "https://example.com/publicacion/prop-106",
  },
];

export const demoLeads: Lead[] = [
  {
    id: "lead-201",
    name: "Andres Gomez",
    role: "Comprador",
    phone: "+573222224444",
    email: "andres.gomez@example.com",
    address: "Chapinero Alto, Bogota",
    lookingFor: "Apartamento de 2 habitaciones para compra",
    budget: 450000000,
    location: "Bogota - Chapinero",
    propertySummary: "Apto 2 hab, 60-80 m2, parqueadero, cerca a zona financiera",
    sourceUrl: "https://facebook.com/groups/inmuebles/posts/201",
  },
  {
    id: "lead-202",
    name: "Paula Restrepo",
    role: "Propietario",
    phone: "+573188889999",
    email: "paula.restrepo@example.com",
    address: "Loma del Escobero, Envigado",
    lookingFor: "Vende casa familiar con patio",
    budget: 690000000,
    location: "Antioquia - Envigado",
    propertyId: "prop-102",
    sourceUrl: "https://example.com/foro/lead-202",
  },
  {
    id: "lead-203",
    name: "Nicolas Bernal",
    role: "Arrendatario",
    phone: "+573145551919",
    email: "nicolas.bernal@example.com",
    address: "Usaquen, Bogota",
    lookingFor: "Apartamento de inversion para alquiler",
    budget: 380000000,
    location: "Bogota - Usaquen",
    propertySummary: "Loft o apto 1 hab, 45-60 m2, cocina abierta, balcon o zona coworking",
    sourceUrl: "https://example.com/grupo/lead-203",
  },
  {
    id: "lead-204",
    name: "Laura Cardenas",
    role: "Arrendador",
    phone: "+573156661212",
    email: "laura.cardenas@example.com",
    address: "Cedritos, Bogota",
    lookingFor: "Arrienda apartamento tipo loft cerca a parque",
    budget: 2600000,
    location: "Bogota - Usaquen",
    propertyId: "prop-105",
    sourceUrl: "https://example.com/grupo/lead-204",
  },
];

export const demoMatches: MatchSuggestion[] = [
  {
    id: "match-301",
    property: demoProperties[0],
    comparisonProperty: demoProperties[2],
    lead: demoLeads[0],
    similarity: {
      gps: 91,
      visual: 84,
      features: 89,
      confidence: 87,
    },
    status: "Pendiente",
  },
  {
    id: "match-302",
    property: demoProperties[1],
    comparisonProperty: demoProperties[3],
    lead: demoLeads[1],
    similarity: {
      gps: 86,
      visual: 78,
      features: 93,
      confidence: 85,
    },
    status: "Pendiente",
  },
  {
    id: "match-303",
    property: demoProperties[4],
    comparisonProperty: demoProperties[5],
    lead: demoLeads[2],
    similarity: {
      gps: 88,
      visual: 81,
      features: 86,
      confidence: 84,
    },
    status: "Pendiente",
  },
];

export const demoTemplates: MessageTemplate[] = [
  {
    id: "tpl-401",
    name: "Primer contacto WhatsApp",
    body:
      "Hola [Nombre_Lead], soy [Nombre_Agente]. Vi que buscas [Tipo_Inmueble] en [Zona]. Tengo una opcion cercana por [Precio]. Te puedo compartir detalles?",
    updatedAt: "2026-06-25T08:00:00.000Z",
  },
];

export const demoRadarActivity: RadarActivityPoint[] = [
  { day: "Jue", publications: 18 },
  { day: "Vie", publications: 24 },
  { day: "Sab", publications: 16 },
  { day: "Dom", publications: 9 },
  { day: "Lun", publications: 31 },
  { day: "Mar", publications: 27 },
  { day: "Mie", publications: 34 },
];

export const demoDemandDistribution: DemandDistributionPoint[] = [
  { name: "Apartamentos", value: 60 },
  { name: "Casas", value: 30 },
  { name: "Locales", value: 10 },
];
